name: oferta_educativa_laboral
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - r-base=4.2
  - r-data.table
  - r-dplyr
  - r-episcout
  - r-ggplot2
  - r-ggthemes
  - r-cowplot
  - r-tidyverse
  - r-skimr
  - r-pander
  - r-log4r
  - r-quarto
  - r-sf
  - r-naniar
  - r-corrplot
  - r-ggrepel
  - r-leaflet
  - r-leaflet.extras
  - r-rnaturalearth
  - r-rnaturalearthdata
  - r-gridextra
  - r-patchwork
  - r-htmltools
  - r-htmlwidgets
  - r-magrittr
  - r-janitor
  - r-openxlsx
  - r-stringi
  - r-circlize
  - r-dbi
  - r-rmariadb
  - r-arules
  - r-arulesviz
  - r-geosphere
  - r-ggalluvial
  - r-factoextra
  - r-factominer
  - r-vcd
  - r-viridis
  - r-ggally
  - r-lpsolve
  - r-mass
  - r-scales
  - r-plotly
  - r-networkd3
  - pip:
    - ruffus
    - cgatcore
    - coverage
    - numpy
    - pandas
    - scipy
    - docopt
