# Not an R package, data science project
# So only for some basic tests when calling R scripts

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CI

jobs:
  r-tests:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: true
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: ubuntu-latest,  r: 'release'}

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install packages
        run: |
          install.packages(c(
            'kableExtra', 'dplyr', 'data.table', 'episcout',
            'testthat', 'magrittr', 'knitr',
            'ggplot2', 'ggthemes',
            'covr', 'lintr', 'styler', 'here', 'withr'
          ))
        shell: Rscript {0}
      - name: Run tests
        run: Rscript -e "testthat::test_dir('tests/testthat')"
